# Working hour

- Describe labor market after 2011.

- Report working hours.

## Environment

```{r}
library(data.table)
library(tidytable)
library(tidyverse)
library(lubridate)
```

## Data status

```{r}
raw <- 
  read_csv("data/hour_time_series.csv")

raw <- 
  read_csv("data/hour_time_series.csv") %>%
  mutate(date = ymd(date),
         year = year(date),
         month = month(date),
         quaterly = if_else(month >= 1 & month <= 3, 1, 0),
         quaterly = if_else(month >= 4 & month <= 6, 2, quaterly),
         quaterly = if_else(month >= 7 & month <= 9, 3, quaterly),
         quaterly = if_else(month >= 10 & month <= 12, 4, quaterly),
         hour = as.numeric(時間総数),
         sex = if_else(性別 == "男", "male", "female")
         ) %>%
  arrange(sex,year,quaterly) %>%
  group_by(sex,year,quaterly) %>%
  mutate(hour = sum(hour)
         ) %>%
  ungroup %>%
  filter(month == 1 | 
           month == 4 | 
           month == 7 | 
           month == 10) %>%
  select(date,
         year,
         month,
         quaterly,
         sex,
         hour) %>%
  na.omit

```

## Working hour

- Report $e_{g,m,y} = hour_{g,m,y}$, where $hour_{g,m,y}$ is working hours.

```{r}
raw %>%
  ggplot(aes(x = date,
             y = hour,
             color = sex)
         ) +
  geom_line() +
  geom_point() +
  theme_bw() +
  ylab("working hour")
```

## Year-to-year difference

- Report change $\tilde e_{g,m,y}=e_{g,m,y}/e_{g,m,y-1}$

```{r}
raw %>%
  arrange(sex,
          quaterly,
          year) %>%
  group_by(sex,
           quaterly) %>%
  mutate(y = hour/lag(hour)) %>%
  ungroup %>%
  filter(year >= 2013) %>%
  ggplot(aes(x = date,
             y = y,
             color = sex)
         ) +
  geom_line() +
  geom_point()  +
  geom_hline(yintercept = 1) +
  ylab("") +
  xlab("") +
  theme_bw() +
  theme(legend.position = "bottom")
```

## Gender gap

- $\tilde e_{male,m,y}-\tilde e_{female,m,y}$

```{r}
raw %>%
  arrange(sex,
          quaterly,
          year) %>%
  group_by(sex,
           quaterly) %>%
  mutate(y = hour/lag(hour)) %>%
  ungroup %>%
  arrange(quaterly,
          year,
          sex) %>%
  group_by(quaterly,
           year) %>%
  mutate(y = y - lag(y)) %>%
  ungroup %>%
  filter(year >= 2013) %>%
  na.omit %>%
  ggplot(aes(x = date,
             y = y)
         ) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0) +
  ylab("") +
  xlab("") +
  theme_bw() +
  theme(legend.position = "bottom")
```


